### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by PwnedG0blin** [Siguza/siguza.github.io#1]
Guten Abend aus Deutschland,
In der Hoffnung das sie mich Nicht Bannen,wegen der frage, möchte ich einfach die frage stellen.
Ist es derzeit möglich auf einem A13 Gerät oder neuer Unter 14.4 ein Jailbreak Update rauszubringen sobald Apple 14.5 veröffentlicht?
Mein neues Gerät kam leider mit 14.4 und in der Einrichtungsphase musste ich um weiter zu kommen auf 14.4.1 Updaten. Dank der Signatur konnte ich dann aber wieder auf 14.4 zurück. Ich weiß eure Arbeit sehr zu schätzen, und würde mich einfach freuen eine kurze Antwort zu erhalten.

Macht weiter so, viele aus der Community danken euch!

Bleibt Gesund

**Comment by Siguza** [comment]
Wenn mir nen 1day in den Schoss fällt, dann kann man drüber reden... ansonsten eher nicht.

**Comment by PwnedG0blin** [comment]
Guten Morgen,
Verstehe. Dann drücke ich mal die Daumen! Möchte nicht ohne Jailbreak leben müssen 🤷‍♂️😅
Dankeschön das du reagiert hast.
